from twitchbot import Command, Message, custom_predicate, choice



@Command('pickup', aliases=['pua','pick','pickupline', 'line','seduction', 'seduce', 'flirt', 'flirtwith'])
async def cmd_function(msg: Message, *args):
    target = msg.arg_or_default(0, msg.author)
    await msg.reply(f'{target} ' + choice([
            'are from tennessee? bc youre the only 10 i see!!!',
        'Hey, my names Microsft. Can I crash at your place tonight?',
        'Are you French? Because Eiffel for you.',
        'Do you like raisins? How do you feel about a date?',
        'There is something wrong with my cell phone. It doesnt have your number in it.',
        'my servers dont go down but i do ;)',
        'If I could rearrange the alphabet, I’d put ‘U’ and ‘I’ together.',
        'ICU in my dreams',
        'Aside from being sexy, what do you do for a living?',
        'I must be a snowflake, because Ive fallen for you.',
        'can I be your ophtalmologist? I cant stop looking into your eyes',
        'I wish I were cross-eyed so I can see you twice.',
        'I must be in a museum, because you truly are a work of art.',
        'Do you believe in love at first sight—or should I walk by again?',
        'Are you a parking ticket? Because you’ve got FINE written all over you.',
        'If you were a Transformer… you’d be Optimus Fine.',
        'you are orienting my objects',
        'Im no photographer, but I can picture us together.',
        'can I take your temperature? Youre looking hot today',
        'Are you a cat because Im feline a connection between us',
        'feel my shirt, know what its made of?? partner material ;)',
        'I’m learning about important dates in history. Wanna be one of them?',
        ' Your hand looks heavy. Here, let me hold it for you.',
        'I drive a motorcycle! Wanna take a ride?',
        'if you were a vegetable, you would be a cute-cumber',
        'If you were unsigned, you would be my minus one',
        'Does your left eye hurt? Because you’ve been looking right all day.',
        'If I said you had a nice body, would you hold it against me?',
        'Is your name Google? Because you have everything I’ve been searching for.',
        'What dinosaur are you? Cute-saur or Sexy-saur',
        'Did you swallow magnets? Cause youre attractive..',
        'Are you a bank loan? Because you got my interest.',
        'Are you a time traveler? Cause I see you in my future!',
        'Kiss me if Im wrong, but dinosaurs still exist, right?',
        'Its not easy to be me.Which is why I need you.',
        'Your heart must be 10x normal size. That must be really painful. Should I call the love doctor?',
        'I dont have a favourite colour, its pretty much whatever you are wearing',
        'You might be the primary reason for global warming',
        'Youre such an exception. Let me catch you!',
        'Are you sitting on F5? Because youre refreshing!',
        'I pretty much only feel comfortable when im around you. Youre like the favourite sweatpants of my life',
        'Do you have a map? I keep getting lost in your eyes.',
        'Do you have a BandAid? I just scraped my knee falling for you.',
        'Do you like Star Wars? Because Yoda only one for me!',
        'Does someone know CPR? Because you are taking my breath away!',
        ' My doctor says Im lacking vitamin U.',
        'You’re so beautiful that you made me forget my pickup line',
        'Did the sun come out or did you just smile at me?',
        'You must be tired because youve been running through my mind all night.',
        'I think youre unchecked, because you make my buffer overflow.',
        'We’re not socks, but I think we’d make a great pair.',
        'Somebody better call God, because he’s missing an angel.',
        'Are you a computer whiz… it seems you know how to turn my software to hardware.',
        'Life without you is like a broken pencil…pointless.',
        'Can I follow you where youre going right now? Because my parents always told me to follow my dreams.',
        'Baby are you a motherboard?, Cause Id "RAM" you all night long',
        'You must be Google Glasses, because you augment my reality',
        'You make my floppy disk turn into a hard drive.',
        'Baby, lets configure our hard drives in master and slave position.',
        'Is your name Diffie-hellman? Lets exchange our keys tonight.',
        'Baby, there is no part of my body that is Micro or Soft',
        ' You make me want to calibrate my joystick without the latest drivers.',
        'Before you, I was a PC without a power outlet.',
        'My "up-time" is better than BSD.',
        'Are you md5? Cus I wanna take a round with you.',
        'Computer techs have skilled fingers if you know what I mean',
        'Everytime I use my Palm, I think of you.',
        'Trust me, Im user friendly.',
        'Are you python code? Cus youre so natural to look at.',
        ' I hope youre an ISO file, because Id like to mount you.',
        'Are you async? Cus I would await for you.',
        'Every time I touch my protected files, I think of you.',
        'Id love to query your tables and natural-join our columns.',
        'Youre a class - and Im the mixin. Let me inject into you.',
        'You had me at "Hello World!"',
        'Baby, you cast my int to a long.',
        ' Id switch to emacs for you.',
        'Why dont we go to my 127.0.0.1, and Ill give you sudo access.',
        'Your smile is proof that the best things in life are free.',
        'If there is one thing I like about you, its that I like more than one thing about you.',
        'Have you hacked my heart??',
        'you are the css to my html',
        'Youre the nothing when people ask me whats on my mind.',
        'there are 10 things I like about you: 1) youre nice. 2) you know binary',
        'Hey girl, are you a loop condition? Cause you keep me coming back to you',
        'Dont try to obfuscate yourself, I already decoded you.',
        'Youre the key to my API',
        '[me != me]. [me += you].',
        'A life without you, would be like a computer without an OS.',
        'You auto-complete me',
        'Are you a double? The thought of you always floats inside my head.',
        'Are you an angel, because your texture mapping is divine!',
        'while(true){ me.in(you); }',
        'Your eyes are far more gorgeous than any source code I have ever seen.',
        'Your beauty rivals the graphics of MW3.',
        'Youre hotter then the bottom of my laptop.',
        'You want to learn about computers huh, youve already passed the first lesson... "Turning Me On" ',
        'are you a n95 mask? cuz I want you on my face',
        'if I was a cpu, youll be my only fan cause I only feel cooler with you',
        'You totally spiked my traffic.',
        'You still use Internet Explorer? You must like it nice and slow.',
        'You must be Windows 95 because you have me so unstable.',
        'You can put a Trojan on my Hard Drive anytime',
        'You are so hot girl that when I first laid eyes on you, I reached a runtime error.',
        'You are my semicolon; always present in everything I do.',
        'You are my initializer: without you, my life would point to nothing (null).',
        'Me gustaría ser un gato para pasar 7 vidas a tu lado.',
        'Robar está mal pero un beso de tu boca sí me lo robaría',
        'We should merge our github repos',
        'you have the brain, I have the charm. lets make a .py',
        ' i dont know your name so can i call u mine',
        'I’d never play hide and seek with you because someone like you is impossible to find',
        'are you an object-oriented programming language? because damn, you have class',
        'Let me tie your shoes, cause I dont want you falling for anyone else.',
        ' everyone is catching covid 19 but im only catching feeling for u',
        'Was you father an alien? Because there’s nothing else like you on Earth!',
        ' If your heart was a prison, I would like to be sentenced for life.'



        ]))